### ISSUE TITLE
Package doesn't support .NETStandard 

### ISSUE THREAD

**Issue by ghost** [Amoenus/PclTimer#5]
I try to install the latest version to .NETStandard 1.5 but I get error 

`Package Amoenus.PclTimer 0.4.0 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package Amoenus.PclTimer 0.4.0 supports: net (.NETFramework,Version=v0.0)`

**Comment by Amoenus** [comment]
Did it work before on older versions? I am not targeting. Net Standart I used old school targeting system. 

If you know how to fix it you are more than welcome to submit a pull request

**Comment by Amoenus** [comment]
@Asseks can you check if new version works for you?
NuGet V3 feed URL (Visual Studio 2015+)
https://www.myget.org/F/amoenus-dev/api/v3/index.json

NuGet V2 feed URL (Visual Studio 2012+)
https://www.myget.org/F/amoenus-dev/api/v2
